""" shared_transaction_id

Revision ID: 703508f0229a
Revises: 74603e10d075
Create Date: 2025-02-06 16:36:29.367656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '703508f0229a'
down_revision: Union[str, None] = '74603e10d075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_transactions', 'shared_transaction_id',
               existing_type=mysql.VARCHAR(length=55),
               comment='',
               existing_nullable=True)
    op.alter_column('payment_gateway_transactions', 'amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='',
               existing_nullable=True)
    op.alter_column('transactionrequests', 'shared_transaction_id',
               existing_type=mysql.VARCHAR(length=55),
               comment='',
               existing_nullable=True)
    op.add_column('transactions', sa.Column('credit_type', sa.String(length=10), nullable=False))
    op.alter_column('transactions', 'shared_transaction_id',
               existing_type=mysql.VARCHAR(length=55),
               comment='',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'shared_transaction_id',
               existing_type=mysql.VARCHAR(length=55),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.drop_column('transactions', 'credit_type')
    op.alter_column('transactionrequests', 'shared_transaction_id',
               existing_type=mysql.VARCHAR(length=55),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('payment_gateway_transactions', 'amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('admin_transactions', 'shared_transaction_id',
               existing_type=mysql.VARCHAR(length=55),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    # ### end Alembic commands ###
